In [5]:
import numpy as np

def resolver_matriz_triangular_superior(a, b):
    n = len(b)
    x = np.zeros(n)
    
    #sust atras
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(a[i, i+1:], x[i+1:]))/ a[i,i] 
        
    print('sol', x)

# Ejemplo 
a = np.array([[2, -1, 3],
              [0,  1, 4],
              [0,  0, 2]])

b = np.array([5, 6, 4])

resolver_matriz_triangular_superior(a, b)

sol [-1.5 -2.   2. ]


In [6]:
import numpy as np

def eliminacion_gauss(a, b):
    
    n = len(b)
    
    ab = np.hstack([a,b.reshape(-1,1)])
    
    for i in range(n):
        if(ab[i,i] == 0):
            raise ValueError("pivote 0")
        
        for j in range (i+1, n):
            m = ab[j,i] / ab[i,i]
            ab[j, i:] = ab[j, i:] - m * ab[i,i:]
      
          
    #sust atras
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(a[i, i+1:], x[i+1:]))/ a[i,i]
        
    print('sol', x)
    
a = np.array([[2, -1, 3],
              [0,  1, 4],
              [0,  0, 2]]) 

b = np.array([5, 6, 4])

eliminacion_gauss(a, b)

sol [-1.5 -2.   2. ]


In [22]:
import numpy as np

def jordan(a, b):
    
    ab = np.hstack([a, b.reshape(-1,1)])
    n = len(b)
    
    for i in range(n):
        # suponiendo aii != 0
        ab[i] = ab[i] / ab[i,i]
        
        for j in range(n):
            if (j != i):
                ab[j] = ab[j] - ab[j, i] * ab[i]
                
    x = ab[:, -1]
    print('sol', x)
    
# ejemplo
a = np.array([[2, -1, -2],
              [-4, 6, 3],
              [-4, -2, 8]], dtype=float)

b = np.array([0, 9, -12], dtype=float)
                
jordan(a, b) 
    

sol [ 0.  2. -1.]


In [21]:
import numpy as np

def cholesky_decomposition(a):
    n = len(a)
    L = np.zeros_like(a)
    
    for k in range(n):
        sum_diagonal = np.sum(L[k, :k]**2)
        L[k,k] = np.sqrt(A[k,k] - sum_diagonal)
        
        for i in range(k+1, n):
            sum_off_diagonal = np.sum(L[i, :k]*L[k, :k])
            L[i, k] = (A[i,k]-sum_off_diagonal) / L[k,k]
            
    print(L)
    
# ej
A = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]], dtype=float)

cholesky_decomposition(A)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
